/** One-time seed data for PSX ticker names + sectors, ported from the
 * legacy app's js/psx-symbols.json (same list used by the static PSX_Trade_Planner).
 * Mirrors qseSeed.ts's role: bundled fallback so the app is never empty on
 * first load. No fundamentals (EPS/DPS) data source exists for PSX yet —
 * only ticker names + sector are available. */

export const PSX_TICKER_NAMES: Record<string, string> = {
  OGDC: 'Oil & Gas Development Company',
  PPL: 'Pakistan Petroleum',
  POL: 'Pakistan Oilfields',
  MARI: 'Mari Petroleum',
  PSO: 'Pakistan State Oil',
  SHEL: 'Shell Pakistan',
  APL: 'Attock Petroleum',
  HASCOL: 'Hascol Petroleum',
  SNGP: 'Sui Northern Gas Pipelines',
  SSGC: 'Sui Southern Gas Company',
  ATRL: 'Attock Refinery',
  NRL: 'National Refinery',
  PRL: 'Pakistan Refinery',
  CNERGY: 'Cnergyico PK',
  HBL: 'Habib Bank',
  UBL: 'United Bank',
  MCB: 'MCB Bank',
  NBP: 'National Bank of Pakistan',
  ABL: 'Allied Bank',
  BAFL: 'Bank Alfalah',
  BAHL: 'Bank AL Habib',
  MEBL: 'Meezan Bank',
  FABL: 'Faysal Bank',
  AKBL: 'Askari Bank',
  BOP: 'The Bank of Punjab',
  BIPL: 'BankIslami Pakistan',
  JSBL: 'JS Bank',
  SILK: 'Silk Bank',
  LUCK: 'Lucky Cement',
  DGKC: 'D.G. Khan Cement',
  MLCF: 'Maple Leaf Cement',
  FCCL: 'Fauji Cement',
  PIOC: 'Pioneer Cement',
  CHCC: 'Cherat Cement',
  KOHC: 'Kohat Cement',
  ACPL: 'Attock Cement Pakistan',
  BWCL: 'Bestway Cement',
  POWER: 'Power Cement',
  GWLC: 'Gharibwal Cement',
  THCCL: 'Thatta Cement',
  FFC: 'Fauji Fertilizer Company',
  EFERT: 'Engro Fertilizers',
  FATIMA: 'Fatima Fertilizer',
  FFBL: 'Fauji Fertilizer Bin Qasim',
  EFUG: 'EFU General Insurance',
  ENGRO: 'Engro Corporation',
  ENGROH: 'Engro Holdings',
  ICI: 'ICI Pakistan',
  LOTCHEM: 'Lotte Chemical Pakistan',
  EPCL: 'Engro Polymer & Chemicals',
  SITARA: 'Sitara Chemical Industries',
  HUBC: 'Hub Power Company',
  KAPCO: 'Kot Addu Power Company',
  KEL: 'K-Electric',
  NPL: 'Nishat Power',
  NCPL: 'Nishat Chunian Power',
  LOTS: 'Lotte Chemical (legacy)',
  PKGP: 'Packages Power',
  NML: 'Nishat Mills',
  GATM: 'Gul Ahmed Textile Mills',
  ILP: 'Interloop',
  KTML: 'Kohinoor Textile Mills',
  CTM: 'Crescent Textile Mills',
  ASTM: 'Ansar Management (Textile)',
  SAPT: 'Sapphire Textile Mills',
  SFL: 'Sapphire Fibres',
  FEROZ: 'Ferozsons Laboratories',
  INDU: 'Indus Motor Company',
  PSMC: 'Pak Suzuki Motor Company',
  HCAR: 'Honda Atlas Cars',
  MTL: 'Millat Tractors',
  AGTL: 'Al-Ghazi Tractors',
  SAZEW: 'Sazgar Engineering Works',
  GHNI: 'Ghandhara Nissan',
  GHGL: 'Ghandhara Industries',
  PSEL: 'Pak Suzuki (legacy code)',
  ATLH: 'Atlas Honda',
  THALL: 'Thal Limited',
  NESTLE: 'Nestle Pakistan',
  UNITY: 'Unity Foods',
  FRIESLAND: 'Friesland Campina Engro',
  MFFL: 'Mitchell\'s Fruit Farms',
  MUREB: 'Murree Brewery',
  COLG: 'Colgate-Palmolive Pakistan',
  NATF: 'National Foods',
  SHEZAN: 'Shezan International',
  MEHT: 'Mehmood Textile (Foods)',
  SYS: 'Systems Limited',
  TRG: 'TRG Pakistan',
  NETSOL: 'NetSol Technologies',
  AIRLINK: 'Air Link Communication',
  AVN: 'Avanceon',
  PTC: 'Pakistan Telecommunication Company',
  WTL: 'WorldCall Telecom',
  OCTOPUS: 'Octopus Digital',
  ISL: 'International Steels',
  ASTL: 'Amreli Steels',
  MUGHAL: 'Mughal Iron & Steel Industries',
  ASL: 'Aisha Steel Mills',
  CSAP: 'Crescent Steel & Allied Products',
  IPAK: 'International Industries',
  PKGS: 'Packages Limited',
  CPPL: 'Century Paper & Board',
  SPL: 'Security Papers',
  JSCL: 'JS Investments',
  AICL: 'Adamjee Insurance',
  IGIHL: 'IGI Holdings',
  PICIC: 'PICIC Insurance',
  PIBTL: 'Pakistan International Bulk Terminal',
  PIAHCLA: 'PIA Holding Company',
  KOSM: 'Kohinoor Spinning',
  TREET: 'Treet Corporation',
  TPLP: 'TPL Properties',
  DAWH: 'Dawood Hercules Corporation',
  DOL: 'Dost Steels',
  PAEL: 'Pak Elektron',
  WAVES: 'Waves Corporation',
  SEARL: 'The Searle Company',
  GLAXO: 'GlaxoSmithKline Pakistan',
  ABOT: 'Abbott Laboratories Pakistan',
  HINOON: 'Highnoon Laboratories',
};

export const PSX_TICKER_SECTORS: Record<string, string> = {
  OGDC: 'Oil & Gas Exploration',
  PPL: 'Oil & Gas Exploration',
  POL: 'Oil & Gas Exploration',
  MARI: 'Oil & Gas Exploration',
  PSO: 'Oil & Gas Marketing',
  SHEL: 'Oil & Gas Marketing',
  APL: 'Oil & Gas Marketing',
  HASCOL: 'Oil & Gas Marketing',
  SNGP: 'Gas Distribution',
  SSGC: 'Gas Distribution',
  ATRL: 'Refinery',
  NRL: 'Refinery',
  PRL: 'Refinery',
  CNERGY: 'Refinery',
  HBL: 'Commercial Banks',
  UBL: 'Commercial Banks',
  MCB: 'Commercial Banks',
  NBP: 'Commercial Banks',
  ABL: 'Commercial Banks',
  BAFL: 'Commercial Banks',
  BAHL: 'Commercial Banks',
  MEBL: 'Commercial Banks',
  FABL: 'Commercial Banks',
  AKBL: 'Commercial Banks',
  BOP: 'Commercial Banks',
  BIPL: 'Commercial Banks',
  JSBL: 'Commercial Banks',
  SILK: 'Commercial Banks',
  LUCK: 'Cement',
  DGKC: 'Cement',
  MLCF: 'Cement',
  FCCL: 'Cement',
  PIOC: 'Cement',
  CHCC: 'Cement',
  KOHC: 'Cement',
  ACPL: 'Cement',
  BWCL: 'Cement',
  POWER: 'Cement',
  GWLC: 'Cement',
  THCCL: 'Cement',
  FFC: 'Fertilizer',
  EFERT: 'Fertilizer',
  FATIMA: 'Fertilizer',
  FFBL: 'Fertilizer',
  EFUG: 'Insurance',
  ENGRO: 'Chemicals / Conglomerate',
  ENGROH: 'Chemicals / Conglomerate',
  ICI: 'Chemicals',
  LOTCHEM: 'Chemicals',
  EPCL: 'Chemicals',
  SITARA: 'Chemicals',
  HUBC: 'Power Generation & Distribution',
  KAPCO: 'Power Generation & Distribution',
  KEL: 'Power Generation & Distribution',
  NPL: 'Power Generation & Distribution',
  NCPL: 'Power Generation & Distribution',
  LOTS: 'Power Generation & Distribution',
  PKGP: 'Power Generation & Distribution',
  NML: 'Textile Composite',
  GATM: 'Textile Composite',
  ILP: 'Textile Composite',
  KTML: 'Textile Composite',
  CTM: 'Textile Composite',
  ASTM: 'Textile Composite',
  SAPT: 'Textile Composite',
  SFL: 'Textile Composite',
  FEROZ: 'Pharmaceuticals',
  INDU: 'Automobile Assembler',
  PSMC: 'Automobile Assembler',
  HCAR: 'Automobile Assembler',
  MTL: 'Automobile Assembler',
  AGTL: 'Automobile Assembler',
  SAZEW: 'Automobile Assembler',
  GHNI: 'Automobile Assembler',
  GHGL: 'Automobile Assembler',
  PSEL: 'Automobile Assembler',
  ATLH: 'Automobile Parts & Accessories',
  THALL: 'Automobile Parts & Accessories',
  NESTLE: 'Food & Personal Care',
  UNITY: 'Food & Personal Care',
  FRIESLAND: 'Food & Personal Care',
  MFFL: 'Food & Personal Care',
  MUREB: 'Food & Personal Care',
  COLG: 'Food & Personal Care',
  NATF: 'Food & Personal Care',
  SHEZAN: 'Food & Personal Care',
  MEHT: 'Food & Personal Care',
  SYS: 'Technology & Communication',
  TRG: 'Technology & Communication',
  NETSOL: 'Technology & Communication',
  AIRLINK: 'Technology & Communication',
  AVN: 'Technology & Communication',
  PTC: 'Technology & Communication',
  WTL: 'Technology & Communication',
  OCTOPUS: 'Technology & Communication',
  ISL: 'Engineering',
  ASTL: 'Engineering',
  MUGHAL: 'Engineering',
  ASL: 'Engineering',
  CSAP: 'Engineering',
  IPAK: 'Engineering',
  PKGS: 'Paper & Board',
  CPPL: 'Paper & Board',
  SPL: 'Paper & Board',
  JSCL: 'Investment Banks',
  AICL: 'Insurance',
  IGIHL: 'Insurance',
  PICIC: 'Insurance',
  PIBTL: 'Transport',
  PIAHCLA: 'Transport',
  KOSM: 'Textile Spinning',
  TREET: 'Household Goods',
  TPLP: 'Real Estate',
  DAWH: 'Chemicals / Conglomerate',
  DOL: 'Engineering',
  PAEL: 'Cable & Electrical Goods',
  WAVES: 'Cable & Electrical Goods',
  SEARL: 'Pharmaceuticals',
  GLAXO: 'Pharmaceuticals',
  ABOT: 'Pharmaceuticals',
  HINOON: 'Pharmaceuticals',
};
